name: currency-exchange-service-CI

on:
  push:
    branches: ["master"]
    paths:
      - 'microservices/currency-exchange-service/**'
      - '.github/workflows/currency-exchange.yml'

  pull_request:
    paths:
      - 'microservices/currency-exchange-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 3. Build Maven project
      - name: Build Project
        working-directory: microservices/currency-exchange-service
        run: mvn -B clean verify

      # 4. Upload JAR Artifact
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: currency-conversion-jar
          path: microservices/currency-exchange-service/target/*.jar

      # 5. Build Docker Image
      - name: Build Docker Image
        run: |
          cd microservices/currency-exchange-service
          docker build -t currency-exchange-service:latest .

      # 6. List Docker Images (debug)
      - name: List Docker Images
        run: docker images

      # 7. Login to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # 8. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag currency-exchange-service:latest ${{ secrets.DOCKER_USER }}/currency-exchange-service:latest

      # 9. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/currency-exchange-service:latest
