name: currency-conversion-service-CI

on:
  push:
    paths:
    
      - 'microservices/currency-conversion-service/**'
      - '.github/workflows/currency-conversion.yml'
      
    branches: ["master"]
  pull_request:
    paths: 
      - 'microservices/currency-conversion-service/**'
     
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: build project
        working-directory: microservices/currency-conversion-service
        run: mvn -B clean verify

      - name: uploadJAR
        uses: actions/upload-artifact@v4
        with:
          name: currency-converter.jar
          path: microservices/currency-conversion-service/target/*.jar

          

  
