name: spring-cloud-ci
on:
  push:
    branches: ["master"]
    paths: 
        - 'microservices/spring-cloud-config-server/**'
        - '.github/workflows/spring-cloud.yml'
  pull_request:
    paths:
      - 'microservices/spring-cloud-config-server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chekout
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: build
        working-directory: microservices/spring-cloud-config-server
        run: mvn -B clean verify
      - name: upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-cloud-server
          path: microservices/spring-cloud-config-server/target/*.jar