name: spring-cloud-ci

on:
  push:
    branches: ["master"]
    paths:
      - 'microservices/spring-cloud-config-server/**'
      - '.github/workflows/spring-cloud.yml'

  pull_request:
    paths:
      - 'microservices/spring-cloud-config-server/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --verbose


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build
        working-directory: microservices/spring-cloud-config-server
        run: mvn -B clean verify -DskipTests
      - name: Build and analyze (SonarCloud)
        working-directory: microservices/currency-exchange-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
         mvn -B clean verify -DskipTests \
         org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
         -Dsonar.projectKey=Kmoha365_micro-services-project \
         -Dsonar.organization=kmoha365 \
         -Dsonar.host.url=https://sonarcloud.io




      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-cloud-config-server-jar
          path: microservices/spring-cloud-config-server/target/*.jar
      - name: build image

        run: |
            cd microservices/spring-cloud-config-server
            docker build -t spring-cloud-server:latest .